# Railway configuration simplifiée pour La-Bringuerie
[build]
  builder = "dockerfile"
  dockerfilePath = "railway-simple.dockerfile"

[deploy]
  startCommand = "npm start --workspace=server"

[[services]]
  [services.variables]
    NODE_ENV = "production"
    NPM_CONFIG_PRODUCTION = "false"