# Railway configuration
[build]
  builder = "dockerfile"
  dockerfilePath = "railway.dockerfile"

[deploy]
  startCommand = "npm start --workspace=server"

[[services]]
  [services.variables]
    NODE_ENV = "production"
    NPM_CONFIG_PRODUCTION = "false"